### ISSUE TITLE
FAQ: Add "Why does Rust not #[derive(Debug)] by default?"

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/prev.rust-lang.org#1073]
Asked on Reddit at least two times:

* https://www.reddit.com/r/rust/comments/8677z1/why_does_rust_not_derivedebug_by_default/
* https://www.reddit.com/r/rust/comments/7y7tz0/is_there_a_reason_rust_does_not_derive_fmtdebug/
  * @graydon's answer: https://www.reddit.com/r/rust/comments/7y7tz0/is_there_a_reason_rust_does_not_derive_fmtdebug/dui5ggc/

@llogiq's answer is a good start; https://www.reddit.com/r/rust/comments/8677z1/why_does_rust_not_derivedebug_by_default/dw378lk/

Not sure where this should go to. Maybe under the "Debugging and Tooling" section.

**Comment by llogiq** [comment]
We should perhaps stress the third point more – that the cost of requiring `#[derive(Debug)]` is acceptable in exchange for a safe default (not having it in the first place).

Incidentally, this argument also applies to auto-deriving `Default`. The code bloat argument is weaker there, because the method is smaller, can likely be `const`ified and inlined.
